import os
from dotenv import load_dotenv
from github import Github, GithubException

load_dotenv()

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN", "")

def get_github_client() -> Github:
    if not GITHUB_TOKEN:
        raise ValueError("GITHUB_TOKEN environment variable is not set.")
    return Github(GITHUB_TOKEN)

def get_pr_changed_files(repo_name: str, pr_number: int) -> list[dict]:
    g    = get_github_client()
    repo = g.get_repo(repo_name)
    pr   = repo.get_pull(pr_number)

    changed_files = []
    for f in pr.get_files():
        if not f.filename.endswith(".py"):
            continue
        if f.status == "removed":
            continue
        try:
            content = repo.get_contents(f.filename, ref=pr.head.sha)
            changed_files.append({
                "filename":  f.filename,
                "content":   content.decoded_content.decode("utf-8"),
                "additions": f.additions,
                "deletions": f.deletions,
                "patch":     f.patch or ""
            })
        except GithubException as e:
            print(f"Could not fetch {f.filename}: {e}")
            continue
    return changed_files

def post_pr_comment(repo_name: str, pr_number: int, comment: str) -> bool:
    try:
        g    = get_github_client()
        repo = g.get_repo(repo_name)
        pr   = repo.get_pull(pr_number)
        pr.create_issue_comment(comment)
        return True
    except GithubException as e:
        print(f"Failed to post PR comment: {e}")
        return False

def format_pipeline_as_comment(result: dict) -> str:
    filename = result.get("filename", "Unknown file")
    review   = result.get("code_review", "")
    triage   = result.get("bug_triage", "")
    backlog  = result.get("sprint_backlog", "")

    return f"""## 🤖 DevMind AI Code Review

**File analyzed:** `{filename}`

---

### 📋 Code Review
{review}

---

### 🐛 Bug Triage
{triage}

---

### 📅 Sprint Backlog
{backlog}

---
*Generated by DevMind — AI-powered code review*
"""